apply plugin: 'java'
apply plugin: 'eclipse'

group = 'ceiba.com.co'
version = '0.0.1-SNAPSHOT'
java {
	sourceCompatibility = '21'
}


repositories {
	mavenCentral()
}

dependencies {

	implementation project(':dominio')
	implementation project(':comun:comun-aplicacion')
	implementation project(':comun:comun-dominio')
	implementation project.ext.springtxt

	testImplementation project.ext.springboottest
	testImplementation project.ext.mockitocore
	testImplementation project.ext.mockitojupiter
}
