jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8084
   servlet:
      context-path: /
      session:
         timeout: 21600s
springdoc:
   swagger-ui:
      path: /swagger-ui.html
spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:postgresql://localhost:5432/gestion_citas_db
      username: postgres
      password: 1303
      hikari:
         poolName: pool
   flyway:
      baseline-on-migrate: true
      clean-on-validation-error: true

